### ISSUE TITLE
ISSUE #19 AYBT Forms

### ISSUE THREAD

**Issue by kirkwhiteman1** [YBNetwork/Issues-Enhancements#20]
We need the ability to let tournament directors add Forms, such as roster and other information for participants.

I have figured out an easy way to do the forms and the functionality is already built-in so it will just require some cosmetic changes.  But I will also add some code.

1. On the Director's Tournament Dashboard - EDIT - "Update Tournament Details Page".  The user already has the ability to write information about "Tournament Rules" and Upload Tournament Rules.  I would like to change the name of this Data Field to read "Tournament Rules & Forms"  I would like the -Upload to read "Tournament Rules & Forms".  I would also like the name of the data field to put something about the format.  Smaller font and italicized.   Such as.
"Upload a .pdf file only"
![image](https://cloud.githubusercontent.com/assets/28075903/26091664/48b58b22-39d2-11e7-8b92-3557c9b0de7f.png)

2. From the Main Page, when user clicks Register - the user is taken to the View Tournament Details Page.  This data field needs to be changed to read. "Tournament Rules & Forms".  Again, smaller font and italicized would be the following "Such as Entry Form, Rosters, Important Information."
![image](https://cloud.githubusercontent.com/assets/28075903/26091716/938077de-39d2-11e7-9cca-42314a52466f.png)

3. Now for the coding.  I would like this form that is uploaded by the director to populate to the Coaches Dashboard - MY TEAMS - Team - "VIEW TOURNAMENT STATUS" for each tournament.  We need to make another column called "Tourney Rules & Forms".  If the director has actually uploaded the form, I would like the data field to say "Download".  If the director has NOT actually uploaded a form, I would like the data field to read "N/A"
![image](https://cloud.githubusercontent.com/assets/28075903/26091779/ef402f9c-39d2-11e7-8706-47d6490805e2.png)

3a. Is there anyway you can squeeze this column between "Date Pmt. Received" & View Tourney Invoice"?  Maybe put "City" on the top line and "State" on the bottom line in their respective field?
3b. While you are at it, I would like the Column Headings to read "Tourney" instead of "Trnmt."

**Comment by bguerrettaz** [comment]
Hi Kirk - I have completed all of your items in this issue.

Please test and confirm that both functionally and visually everything
looks correct.

Thanks,
Blake

**Comment by kirkwhiteman1** [comment]
Hi Blake:

Looks good.  I did a quick test on my login as coach:
kwhiteman@dtechserv.com

I have my B6th grade team registered for my Spring Event - and that will
NOT download from my coaches login - but the other 3 tournaments do
download?

Kirk
[image: Inline image 1]

**Comment by kirkwhiteman1** [comment]
Forget it - I backed out and did it again and it worked fine.  Computer
must have been slow.!

**Comment by bguerrettaz** [comment]
Sounds good, so everything looks good? If so I can close.  Also, what is the next priority issue?

**Comment by kirkwhiteman1** [comment]
Yes, good to close.

 

I need that ADMIN report for AYBT Nationals, can’t remember what issue.  But that is one we can start to work on.

 

Yours in Hoops,

 

Kirk Whiteman

217.714.7263

 <http://www.aybtour.com/> 

 <http://www.ybnetwork.net/>      <https://www.facebook.com/americanyouthbasketballtour/>      <https://twitter.com/AybTour>      <https://www.instagram.com/aybtour/>
