### ISSUE TITLE
Report specifically for our 4 AYBT Nationals - Due June 15th

### ISSUE THREAD

**Issue by bguerrettaz** [YBNetwork/Issues-Enhancements#21]
1. ADMIN report accessed from ADMIN page.
I need a report specifically for our 4 AYBT Nationals that will pull the following information.
B3rd [gender GRADE]
Team name
Head Coach 
Cell phone
All AYBT Events & Registration Status

(Basically i need a list of every team going to one of our 4 National AYBT Tournaments showing what AYBT Events each team scheduled for a National Tournament has participated.  Every team going to a National event will receive 25 cash back for every AYBT they were scheduled for previously up to 100.  For every additional National  (after the first one) a team will get back $150 cash at their 2nd national. If team plays a 3rd national they get back $300 and if team plays in all 4 nationals they get back $545.  The national rebates also includes the $25 per AYBT rebate up to 100 too.  

So if a team plays in 4 AYBT regular tournaments and 4 AYBT National tournaments a team would get back 645 in cash.

I just need a report.  We can figure out calculations

**Comment by bguerrettaz** [comment]
Hi Kirk - I just wanted you to know that I've already started this work.  I have noticed that the 'Reports' section under the admin site hasn't really been used or started.  So this first report will take me some time, as I have to set it all up (it's all currently dummy text in Latin).

6-9 hours depending on different complexities.  

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Kirk,

I have derived the query and dataset for the report as well as started the code to place this report on the admin reporting site.  As I said before, the admin reporting site wasn't previously started, so I have to build that out as well.

I have attached the report in Excel format, this is what will show in the admin reporting site, once completed (it'll be formatted better).

[AYBTNationalsReport_05.26.17.xlsx](https://github.com/YBNetwork/Issues-Enhancements/files/1032103/AYBTNationalsReport_05.26.17.xlsx)

Please look through this and let me know if there are any suggested changes before getting it installed on the site.

Thanks,
Blake

Here is the query for reference:

select 
    
t.profile_team_gender, 
    t.profile_team_grade, 
    t.profile_team_name, 
    t.head_coach_name, 
    t.cell_phone, 
    tr.tournament_name, 
    st.dateRegistered, 
    st.paymentDate, 
    st.balance_due, 
    st.amount_paid
from team t
join steams st on t.id = st.sYBNTeamId
join tournament tr on st.sTournamentId = tr.id
where tr.tournament_name not like 'AYBT NATIONAL%' AND tr.tournament_name like 'AYBT%' and t.id IN
(
    select st.sYBNTeamId from steams st
    where st.sTournamentId IN
(
    SELECT id FROM `tournament` 
    where tournament_name like 'AYBT NATIONAL%'
)
)
order by tr.tournament_name, t.profile_team_name

**Comment by kirkwhiteman1** [comment]
Looks good.  But which AYBT Nationals Report?  We have 4 Nationals

 

Bloomington, IL

Grand Rapids, MI

Ft. Wayne, IN

Spooky Nook (PA)

 

I am not sure which AYBT Nationals these teams are associated with.

 

Yours in Hoops,

 

Kirk Whiteman

217.714.7263

 <http://www.aybtour.com/> 

 <http://www.ybnetwork.net/>      <https://www.facebook.com/americanyouthbasketballtour/>      <https://twitter.com/AybTour>      <https://www.instagram.com/aybtour/>

**Comment by bguerrettaz** [comment]
I'll add that column to the report, this report is showing the teams that
currently have 1 or more AYBT National registrations and the other
tournaments they have registered for outside of the Nationals.

**Comment by bguerrettaz** [comment]
Hi Kirk,

Because of the way the data tables are designed, it was a little more clear to include the AYBT National events and sort by coach name and tournament name.

Please see the attached and let me know if this report is what you'd like to see.  Because of the number of rows, I won't display this report in the admin console, but rather, when a user clicks the report, it'll download the Excel version. 

Does that sound good?

Thanks,
Blake

[AYBTNationalsReport_05.31.17.xlsx](https://github.com/YBNetwork/Issues-Enhancements/files/1041705/AYBTNationalsReport_05.31.17.xlsx)

**Comment by kirkwhiteman1** [comment]
Blake:

This report will be used to give rebates to teams at the team registration desk of each National Tournament.  So I want to include all the teams in the registration report except Dropped teams.  So I would like to include the {Registration Status}

Also, would it be possible to have 4 reports, one for each Nationals.  That way it will be easier to sort and group teams to arrive at how much of a rebate to give them.  Including all the Nationals in one report is too cumbersome to sort and figure out who we owe money to.

![image](https://cloud.githubusercontent.com/assets/28075903/26637765/fa53f9c6-45e5-11e7-9147-a9724ba93312.png)

**Comment by bguerrettaz** [comment]
Hi Kirk,

I have made the desired changes.

Please login to the admin console and click on reports.  There you'll see
the 4 new reports in the format you've requested.  These are downloaded as
.CSV files, meaning they open in Excel.  To resize the columns, just double
click in between each one (to show all content).

Let me know your thoughts.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
I think we're good to close, let me know if you need anything else for this.

Blake
