### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by bguerrettaz** [YBNetwork/Issues-Enhancements#5]
Placeholder, more to come...

**Comment by kirkwhiteman1** [comment]
Brian & Blake:

My time has freed up during the weekdays.  Brian - have you been able to locate Darrell's old code for Step 5a?  This Issues should be titled Scheduling & Results.

I need expert guidance on this issue.  I know what I want but not sure how to present it.  I feel a face to face whiteboard session is needed.

**Comment by bguerrettaz** [comment]
Closing due to new issue opening #25
