### ISSUE TITLE
Coach's Dashboard - My Teams - View Team - "My Tournament(s) Status"

### ISSUE THREAD

**Issue by kirkwhiteman1** [YBNetwork/Issues-Enhancements#8]
We need to reformat the "My Tournament(s)" page.  Please see attached document.

[YBN Coach Dashboard MY TEAMS View Teams My Tournament(s) Status.xlsx](https://github.com/YBNetwork/Issues-Enhancements/files/962725/YBN.Coach.Dashboard.MY.TEAMS.View.Teams.My.Tournament.s.Status.xlsx)

**Comment by kirkwhiteman1** [comment]
Please note - I have added a couple data fields to this issues.  The purp
[YBN Coach Dashboard MY TEAMS View Teams My Tournament(s) Status.xlsx](https://github.com/YBNetwork/Issues-Enhancements/files/964884/YBN.Coach.Dashboard.MY.TEAMS.View.Teams.My.Tournament.s.Status.xlsx)
ose of these changes is to allow the coach to print off the popup information.  This print off will contain basically an invoice of sorts

**Comment by bguerrettaz** [comment]
Did I read this line correctly?  

-When user (coach) clicks on View Tournament Details I would like this to Say "View Tournament Invoice"

So change the 'View Tournament Details' button to 'View Tournament Invoice'?

Just want to confirm.

**Comment by kirkwhiteman1** [comment]
Correct

Kirk Whiteman

**Comment by bguerrettaz** [comment]
Hi Kirk,

I'm making good progress on this issue.  If you have a few moments, I'm hoping you can go out and validate what is currently done.  Please go to the tournament status page and make sure that looks as desired.  Key changes on that page:

- Cleaned up of some code issues
- Renamed some headers
- Renamed to 'View Tournament Invoice'
- Made the special request text area 'hot', meaning, when you type something in, and hit the submit button, its saved to the database without doing a full page reload (using AJAX and jQuery)
- Started work on the director/invoice popup:

![image](https://cloud.githubusercontent.com/assets/5695475/25663776/2f4d0e06-2fde-11e7-9d35-30aaf464b32f.png)

The items highlighted in yellow is still work in progress, I need to bring in the necessary data and hook it to the proper fields.  Does this look like what you're wanting overall?

Could of questions on that popup:

- Can there be only 1 team listed, or is that 1 to many?
- For the registration due date, how do you want that to be shown?  If they are registered show 'Registered On' and if not, the date registration needs to be completed on?  That was just confusing from the spec doc.

Please let me know your thoughts.

Thanks,
Blake

**Comment by kirkwhiteman1** [comment]
Yes.  Looks great.

We are only showing 1 team.

Registration Due should actually be the data field from the director
dahsboard (Registration Deadline)

Kirk Whiteman

**Comment by bguerrettaz** [comment]
Hi Kirk - ok, I think I have everything in line with your requirements.  Can you please take a look over everything that this issues encompasses and let me know your thoughts?  If its complete with no changes, then we can close this issue (it gets archived and can always be reopened).

Thanks,
Blake

**Comment by kirkwhiteman1** [comment]
Just checked it out and looks good to close.

**Comment by kirkwhiteman1** [comment]
Confirmed

Kirk Whiteman
